base_django/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^sources/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users_confirm_reset.html',
         'post_reset_redirect': '/user/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^user/password/done/$', password_reset_complete,
        {'template_name': 'users_pass_done.html'}),
    url(r'^', include('utils.urls', namespace="utils")),
    url(r'^', include('users.urls', namespace="users")),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    )

from .forms import PasswordResetForm
from .ajaxs import *
from .views import *


urlpatterns = [
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),

     # Reset password all users
    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'users_forgot.html',
         'password_reset_form': PasswordResetForm},
        name="forgot"),
    url(r'^accounts/password/done/$', password_reset_done,
        {'template_name': 'users_pass_reset_done.html'},
        name='reset_done'),

    # Urls Access Super Admin
    url(r'^lista-usuarios/$', ListUsersView.as_view(), name="lista_users"),
    url(r'^perfil/(?P<pk>\d+)/$', ModalsPerfil.as_view(),
        name="modal_perfil"),
    url(r'^registrar/$', RegisterView.as_view(), name="registrar"),

    # Ajax list Users, for Super Admin
    url(r'^listar-usuarios/$', ListUsersAjaxView.as_view(),
        name="listar_users"),
]

users/models.py
# -*- encoding: utf-8 -*-
"""!
Modelo que construye los modelos de datos de los usuarios

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
@date 18-01-2017
@version 1.0.0
"""
from django.db import models
from django.contrib.auth.models import (
    Group, User
    )

from utils.models import (
    TipoDocumento
    )

"""
Se agrega un campo de descripcion al modelo group para describir el grupo de usuarios
"""
Group.add_to_class('descripcion', models.TextField(blank=True))


class UserProfile(models.Model):
    """!
    Clase que construye el modelo de datos para el perfil de usuario

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 18-01-2017
    @version 1.0.0
    """
    fk_user = models.OneToOneField(User)
    fk_tipo_documento = models.ForeignKey(TipoDocumento)
    id_perfil = models.PositiveIntegerField(unique=True, verbose_name='Documento de identidad')

    class Meta:
        """!
        Clase que construye los meta datos del modelo

        @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
        @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
        @date 18-01-2017
        @version 1.0.0
        """
        ordering = ('fk_user',)
        verbose_name = 'Perfil de usuario'
        verbose_name_plural = 'Perfiles de usuarios'
        db_table = 'users_perfil'

    def __str__(self):
        return self.fk_user.username

users/views.py
# -*- encoding: utf-8 -*-
"""!
Vista que controla los procesos de los usuarios

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
@date 09-01-2017
@version 1.0.0
"""
from django.core import serializers
from django import forms
from django.db.models import Q
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (
    authenticate, logout, login
)

from django.contrib.admin.models import LogEntry, ADDITION, CHANGE, DELETION
from django.contrib.auth.models import (
    Group, Permission, User
)
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.contrib.contenttypes.models import ContentType
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import (
    reverse_lazy, reverse
)

from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.views.generic.edit import (
    FormView, UpdateView
)
from multi_form_view import MultiModelFormView

from .models import UserProfile
from .forms import (
    FormularioLogin, FormularioAdminRegistro, FormularioUpdate,
    FormularioAdminRegPerfil, FormularioRegistroComun
)

from utils.views import (
    LoginRequeridoPerAuth
)
from utils.messages import MENSAJES_LOGIN, MENSAJES_START

class LoginView(FormView):
    """!
    Muestra el formulario de ingreso a la aplicación 

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    form_class = FormularioLogin
    template_name = 'users_login.html'
    success_url = '/inicio/'
    model = UserProfile

    def form_valid(self, form):
        """
        Valida el formulario de logeo
        @return: Dirige a la pantalla inicial de la plataforma
        """
        usuario = form.cleaned_data['usuario']
        contrasena = form.cleaned_data['contrasena']
        if '@' in usuario:
            try:
                usuario = User.objects.get(email=usuario).username
            except:
                messages.error(self.request, MENSAJES_LOGIN['CORREO_INVALIDO'] % (usuario))
        usuario = authenticate(username=usuario, password=contrasena)
        if usuario is not None:
            login(self.request, usuario)
            self.request.session['permisos'] = list(usuario.get_all_permissions())
            try:
                grupos = usuario.groups.all()
                grupo = []
                if len(grupos) > 1:
                    for g in grupos:
                        grupo += str(g),
                else:
                    grupo = str(usuario.groups.get())
            except:
                grupo = "No pertenece a un grupo"

            self.request.session['grupos'] = grupo

            if self.request.POST.get('remember_me') is not None:
                # Session expira a los dos meses si no se deslogea
                self.request.session.set_expiry(1209600)
            messages.info(self.request, MENSAJES_START['INICIO_SESION'] % (usuario.first_name, usuario.username))
        else:
            user = User.objects.filter(username=form.cleaned_data['usuario'])
            if user:
                user = user.get()
                if not user.is_active:
                    self.success_url = reverse_lazy('users:login')
                    messages.error(self.request, MENSAJES_LOGIN['CUENTA_INACTIVA'])
            else:
                self.success_url = reverse_lazy('users:login')
                messages.warning(self.request, MENSAJES_LOGIN['LOGIN_USUARIO_NO_VALIDO'])

        return super(LoginView, self).form_valid(form)


class LogOutView(RedirectView):
    """!
    Salir de la apliacion

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    permanent = False
    query_string = True

    def get_redirect_url(self):
        """!
        Dirige a la pantalla del login
        @return: A la url del login
        """
        logout(self.request)
        return reverse_lazy('users:login')


class ListUsersView(LoginRequeridoPerAuth, TemplateView):
    """!
    Listar usuarios de la apliacion

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    template_name = "users_list.html"
    model = User
    success_url = reverse_lazy('users:lista_users')
    group_required = [u"Super Admin"]

    def __init__(self):
        super(ListUsersView, self).__init__()


    def post(self, *args, **kwargs):
        '''
        Cambia el estado activo a el usuario
        @return: Dirige a la tabla que muestra los usuarios de la apliacion
        '''
        accion = self.request.POST
        activar = accion.get('activar', None)
        inactivar = accion.get('inactivar', None)
        estado = False

        if activar is not None:
            user = activar
            estado = True
        elif inactivar is not None:
            user = inactivar
            estado = False
        else:
            messages.error(self.request, "Esta intentando hacer una accion incorrecta")      
        try:
            user_act = self.model.objects.get(pk=user)
            user_act.is_active = estado
            user_act.save()
            if estado:
                messages.success(self.request, "Se ha activado el usuario: %s" % (str(user_act)))
            else:
                messages.warning(self.request, "Se ha inactivado el usuario: %s" % (str(user_act)))
        except:
            messages.info(self.request, "El usuario no existe")
        return redirect(self.success_url)


class StartView(LoginRequiredMixin, TemplateView):
    """!
    Muestra el inicio de la plataforma

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    @return: El template inicial de la plataforma
    """
    template_name = "home.html"

    def dispatch(self, request, *args, **kwargs):
        """
        Envia una alerta al usuario que intenta acceder sin estar logeado
        @return: Direcciona al login en caso de no poseer permisos, en caso contrario usa la clase
        """
        if not request.user.is_authenticated:
            messages.warning(self.request, "Debes iniciar Sessón")
            return self.handle_no_permission()
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        """Use this to add extra context."""
        try:
            perfil = UserProfile.objects.select_related().get(fk_user=self.request.user.id)
        except:
            perfil = None
        context = super(StartView, self).get_context_data(**kwargs)
        context['userprofile'] = perfil
        return context


class RegisterView(LoginRequeridoPerAuth, MultiModelFormView):
    """!
    Muestra el formulario de registro de usuarios

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    template_name = "users_register.html"
    form_classes = {
      'user': FormularioAdminRegistro,
      'user_perfil': FormularioAdminRegPerfil,
    }
    success_url = reverse_lazy('utils:inicio')
    model = Group
    model_permi = Permission
    group_required = [u"Super Admin"]
    record_id=None

    def get_context_data(self, **kwargs):
        """
        Carga el formulario en la vista,para registrar usuarios
        @return: El contexto con los objectos para la vista
        """
        return super(RegisterView, self).get_context_data(**kwargs)

    def forms_valid(self, forms, **kwargs):
        """
        Valida el formulario de registro del perfil de usuario
        @return: Dirige con un mensaje de exito a el home
        """
        nuevo_usuario = forms['user'].save()
        nuevo_perfil = forms['user_perfil'].save(commit=False)
        nuevo_perfil.fk_user = nuevo_usuario
        nuevo_perfil.save()
        usuario = forms['user'].cleaned_data['username']
        grupos = forms['user'].cleaned_data['groups']
        for group in grupos:
            # Agrega a el usuario al(los) grupo(s) seleccionado(s)
            nuevo_usuario.groups.add(group.pk)
        model_user = ContentType.objects.get_for_model(User).pk
        LogEntry.objects.log_action(
            user_id=self.request.user.id,
            content_type_id=model_user,
            object_id=nuevo_usuario.id,
            object_repr=str(nuevo_usuario.username),
            action_flag=ADDITION)
        messages.success(self.request, "Usuario %s creado con exito\
                                       " % (str(usuario)))
        return super(RegisterView, self).forms_valid(forms)

        
class ModalsPerfil(LoginRequeridoPerAuth, MultiModelFormView):
    """!
    Construye el modals para la actualizacion del usuario

    @author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    model = UserProfile
    form_classes = {
      'user': FormularioUpdate,
      'user_perfil': FormularioAdminRegPerfil,
    }

users/templates/users_confirm_reset.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}'=Django-Cambiar Password='{% endblock title %}
{% block extras_constantes %}
{% endblock extras_constantes %}
{% block extras_css %}
<link rel="stylesheet" href="{% static 'css/custom_login.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/font_varelaround.css'  %}" rel='stylesheet' type='text/css'>
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">
</script>
{% endblock extras_js %}
{% block contenido %}
<!-- Where all the magic happens -->
<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
    <div class="logo">Recuperar contraseña</div>
    <!-- Main Form -->
    <div class="login-form-1">
    {% if validlink %}
    <form id="forgot-password-form" class="text-left" method="post">
            <div class="etc-login-form">
                <p>Por favor ingrese su nueva contraseña dos veces.<br />
                        Así podremos verificar que es correcta.</p> 
            </div>
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                </div>
                <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
            </div>
        </form>
        {% else %}
        <div class="etc-login-form">
            <h1>Se intento recuperar la contraseña, pero fallo.</h1>
            <p align="center">El vínculo de recuperación de contraseña es inválido, <br />
            Posiblemente ya ha sido usado <br />
            Por favor solicite una nueva contraseña.</p>
        {% endif %}
        </div>
    </div>
    <!-- end:Main Form -->
</div>
{% endblock contenido %}
{% block custom_js%}
<script src="{% static 'js/custom_login.js' %}"></script>
{% endblock custom_js%}

users/templates/users_forgot.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}'=Django-Forgot Password='{% endblock title %}
{% block extras_constantes %}
{% endblock extras_constantes %}
{% block extras_css %}
<link rel="stylesheet" href="{% static 'css/custom_login.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/font_varelaround.css'  %}" rel='stylesheet' type='text/css'>
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">
</script>
{% endblock extras_js %}
{% block contenido %}
<!-- Where all the magic happens -->
<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
    <div class="logo">Forgot Password</div>
    <!-- Main Form -->
    <div class="login-form-1">
        <form id="forgot-password-form" class="text-left" method="post">
            <div class="etc-login-form">
                <p>When you fill in your registered email address, you will be sent instructions on how to reset your password.</p>
            </div>
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        {% csrf_token %}
                        {{ form.email }}
                    </div>
                </div>
                <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
            </div>
            <div class="etc-login-form">
                <p>already have an account? <a href="{% url 'users:login'%}">login here</a></p>
                <p>new user? <a href="#">create new account</a></p>
            </div>
        </form>
    </div>
    <!-- end:Main Form -->
</div>
{% endblock contenido %}
{% block custom_js%}
<script src="{% static 'js/custom_login.js' %}"></script>
{% endblock custom_js%}

users/templates/users_list.html
{% extends 'utils_start.html' %}
{% block title %} Users List {% endblock title%}
{% load staticfiles %}
{% block extras_css %}
    <link rel="stylesheet" href="{% static 'DataTables/media/css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/checked_img.css' %}">
{% endblock extras_css %}
 {% block extras_constantes %}
    <script type="text/javascript">
            // Objeto Json lista de usuarios
            var URL = "{% url 'users:listar_users' %}"
            var user = "{{ request.user.pk }}"
            ruta = "{% url 'users:modal_perfil' request.user.pk %}";
            id_user = {{request.user.pk}};
        </script>
{% endblock extras_constantes %}
{% block extras_js %}
    <script src="{% static 'DataTables/media/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'custom_datatable/listDataTable.js' %}" type="text/javascript"></script>
    <script src="{% static 'start/modals.js' %}"></script>
    <script type="text/javascript">
          id_user = {{request.user.pk}};
    </script>   
{% endblock extras_js %}
{% block content_center %}
<div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    <a class="glyphicon glyphicon-list" id="menu-toggle"></a>
                    <section class="content-header">
                      <h2>
                        Lista de Usuarios
                        <small>Muestra los datos de todos los usuarios Registrados</small>
                      </h2>
                    </section>
                    <section class="content">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="box box-primary">
                                    <div class="box-header">
                                    <i class="fa fa-list"></i>
                                    <h3 class="box-title"> Lista de Usuarios</h3>
                                    </div>
                                    <div class="col-lg-3">
                                        <a href="{% url 'users:registrar'%}" class="glyphicon glyphicon-plus btn btn-block btn-primary"> Agregar Usuario</a>
                                    </div><br><br>
                                    <div class="box-body pad table-responsive">
                                    <form id="forma_activar" method="post">
                                    {% csrf_token %}
                                        <table id="datatable" class="diplay">
                                            <thead>
                                                <tr>
                                                    <th>Usuario</th>
                                                    <th>Nombres y Apellidos</th>
                                                    <th>Email</th>
                                                    <th>Fecha de registro</th>
                                                    <th>Ultima Fecha de Ingreso</th>
                                                    <th>Activo/Inactivo</th>
                                                    <th>Grupo</th>
                                                    <th>Activar/Inactivar Usuarios</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    </div>
                </div>
            </div>
</div>
{% endblock content_center %}

users/templates/users_login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}'=Django-Login='{% endblock title %}
{% block extras_constantes %}
{% endblock extras_constantes %}
{% block extras_css %}
<link rel="stylesheet" href="{% static 'css/custom_login.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/font_varelaround.css'  %}" rel='stylesheet' type='text/css'>
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">
     /**
     * @brief Función para recargar el captcha vía json
     * @param element Recibe el botón
     */
    function refresh_captcha(element) {
        $form = $(element).parents('form');
        var url = location.protocol + "//" + window.location.hostname + ":" + location.port + "/captcha/refresh/";

        $.getJSON(url, {}, function(json) {
            $form.find('input[name="captcha_0"]').val(json.key);
            $form.find('img.captcha').attr('src', json.image_url);
        });

        return false;
    } 
$(document).ready(function() {
     
    $('#id_captcha_1').attr('class','form-control');
    $('#id_captcha_1').attr('placeholder','Ingresa los 4 caracteres');
});
</script>
{% endblock extras_js %}
{% block contenido %}
<!-- Where all the magic happens -->
<!-- LOGIN FORM -->
<div class="text-center" style="padding:50px 0">
    <div class="logo">Login Base Django</div>
    <!-- Main Form -->
    <div class="login-form-1">
        <form id="login-form" class="text-left" method="post">
        {% csrf_token %}
            <div class="login-form-main-message"></div>
            <div class="main-login-form">
                <div class="login-group">
                    <div class="form-group">
                        {{ form.usuario }}
                    </div>
                    <div class="form-group">
                        {{ form.contrasena }}
                    </div>
                    <div class="form-group login-group-checkbox">
                        {{form.remember_me}}
                        <label for="id_remember_me">Recordarme</label>
                    </div>
                    <div class="form-group has-feedback {% if form.captcha.errors %}has-error{% endif %}">
                    <a onclick="refresh_captcha(this);" style="cursor: pointer">
                      <span class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="Presione para recargar la imagen del captcha"></span>
                    </a>
                    {{form.captcha}}
                  </div>
                </div>
                <button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>
            </div>
            <div class="etc-login-form">
                <p>forgot your password? <a href="{% url 'users:forgot' %}">click here</a></p>
                <p>new user? <a href="#">create new account</a></p>
            </div>
        </form>
    </div>
    <!-- end:Main Form -->
</div>
{% endblock contenido %}
{% block custom_js%}
<script src="{% static 'js/custom_login.js' %}"></script>
{% endblock custom_js%}

users/templates/users_modalsProfile.html
{% block extra_css %}
{% load staticfiles %}
<link type="text/css" rel="stylesheet" href="{% static 'jquery-entropizer-master/dist/css/jquery-entropizer.min.css' %}" />
{% endblock extra_css %}
{% block extra_js %}
<script type="text/javascript" src="{% static 'jquery-entropizer-master/lib/entropizer.js' %}"></script>
<script type="text/javascript" src="{% static 'jquery-entropizer-master/dist/js/jquery-entropizer.min.js' %}"></script>
<script type="text/javascript" src="{% static 'users/user_register.js' %}"></script>
{% endblock extra_js %}
<!-- Inicio Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active" id="cuentas">
      <a href="#cuenta" aria-controls="cuenta" role="tab" data-toggle="tab">Cuenta de Usuario</a>
    </li>
    <li role="presentation" id="perfiles">
      <a href="#perfil" aria-controls="perfil" role="tab" data-toggle="tab">Perfil de Usuario</a>
    </li>
  </ul>
  <!-- Fin Nav tabs -->
  <!-- Inicio Tab panes -->
  <form id="form_perfil" action="{% url 'users:modal_perfil' upUser.fk_user.pk %}" method="post">
  <div class="tab-content">
  <div role="tabpanel" class="tab-pane active" id="cuenta">
      <h3>Actualizar la cuenta de usuario </h3>
      {% csrf_token %}
    <div class="form-group has-feedback">
      {{ forms.user.email }}
      <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
    </div>
    {% if 'Super Admin' in request.session.grupos %}
    <div class="row">
          <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              {{ forms.user.is_staff}}
            </label>
              {{ forms.user.is_staff.label}}
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <div class="checkbox icheck">
            <label>
              {{ forms.user.is_active}}
            </label>
              {{ forms.user.is_active.label}}
            </div>
          </div>
          <!-- /.col -->
        </div>
        <div class="form-group has-feedback">
          <label>
                Grupos de Usuario
          </label>
          {{ forms.user.groups }}
        </div>
    {% endif %}
    </div>
    <div role="tabpanel" class="tab-pane" id="perfil">
      <h3>Actualizar el Perfil del Usuario</h3>
        <div class="form-group has-feedback">
          {{ forms.user.first_name }}
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          {{ forms.user.last_name }}
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          {{ forms.user_perfil.fk_tipo_documento }}
          <span class="glyphicon glyphicon-list form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          {{ forms.user_perfil.id_perfil }}
          <span class="glyphicon glyphicon-list form-control-feedback"></span>
        </div>
    </div>
  <div class="modal-footer">
  <input type="submit" value="Actualizar Perfil" class="btn btn-success"/>
  </form>
<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</div>
</div>

users/templates/users_pass_done.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}'=Django-Password Recuperada='{% endblock title %}
{% block extras_constantes %}
{% endblock extras_constantes %}
{% block extras_css %}
<link rel="stylesheet" href="{% static 'css/custom_login.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/font_varelaround.css'  %}" rel='stylesheet' type='text/css'>
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">
</script>
{% endblock extras_js %}
{% block contenido %}
<!-- Where all the magic happens -->
<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
    <div class="logo">Recuperar contraseña</div>
    <!-- Main Form -->
    <div class="login-form-1">
            <div class="etc-login-form">
                <p>Tu contraseña ha sido definida. Ya puedes iniciar sesión de nuevo</p>  
                    <p><a href="{% url 'users:login' %}">Iniciar sesión</a></p>  
            </div>
    </div>
    <!-- end:Main Form -->
</div>
{% endblock contenido %}
{% block custom_js%}
{% endblock custom_js%}

users/templates/users_pass_reset_done.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}'=Django-Recupeara Password='{% endblock title %}
{% block extras_constantes %}
{% endblock extras_constantes %}
{% block extras_css %}
<link rel="stylesheet" href="{% static 'css/custom_login.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
<link href="{% static 'css/font_varelaround.css'  %}" rel='stylesheet' type='text/css'>
{% endblock extras_css %}
{% block extras_js %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script type="text/javascript">
</script>
{% endblock extras_js %}
{% block contenido %}
<!-- Where all the magic happens -->
<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
    <div class="logo">Recuperar contraseña</div>
    <!-- Main Form -->
    <div class="login-form-1">
            <div class="etc-login-form">
                <p align="justify">Hemos enviado las instrucciones de como recuperar la contraseña a la dirección de correo electrónico especificada</p>  
                <p>Estarás recibiendo el correo pronto.</p>  
            </div>
    </div>
    <!-- end:Main Form -->
</div>
{% endblock contenido %}
{% block custom_js%}
{% endblock custom_js%}