base_django/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import (
    password_reset_confirm, password_reset_complete
    )

from users.forms import SetPasswordForm

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^sources/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        password_reset_confirm,
        {'template_name': 'users_confirm_reset.html',
         'post_reset_redirect': '/user/password/done/',
         'set_password_form': SetPasswordForm},
        name='password_reset_confirm'),
    url(r'^user/password/done/$', password_reset_complete,
        {'template_name': 'users_pass_done.html'}),
    url(r'^', include('utils.urls', namespace="utils")),
    url(r'^', include('users.urls', namespace="users")),
]

users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.views import (
    password_reset, password_reset_done,
    )

from .forms import PasswordResetForm
from .ajaxs import *
from .views import *


urlpatterns = [
    url(r'^$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogOutView.as_view(), name="logout"),

     # Reset password all users
    url(r'^accounts/password/reset/$', password_reset,
        {'post_reset_redirect': '/accounts/password/done/',
         'template_name': 'users_forgot.html',
         'password_reset_form': PasswordResetForm},
        name="forgot"),
    url(r'^accounts/password/done/$', password_reset_done,
        {'template_name': 'users_pass_reset_done.html'},
        name='reset_done'),

    # Urls Access Super Admin
    url(r'^lista-usuarios/$', ListUsersView.as_view(), name="lista_users"),
    url(r'^perfil/(?P<pk>\d+)/$', ModalsPerfil.as_view(),
        name="modal_perfil"),
    url(r'^registrar/$', RegisterView.as_view(), name="registrar"),

    # Ajax list Users, for Super Admin
    url(r'^listar-usuarios/$', ListUsersAjaxView.as_view(),
        name="listar_users"),
]

utils/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^inicio/$', StartView.as_view(), name='inicio'),
    url(r'^pais-autocomplete/$', PaisAutocomplete.as_view(),
    name='pais_autocomplete',
    ),
    url(r'^estado-autocomplete/$', EstadoAutocomplete.as_view(),
    name='estado_autocomplete',
    ),
    url(r'^municipio-autocomplete/$', MunicipioAutocomplete.as_view(),
    name='municipio_autocomplete',
    ),
    url(r'^parroquia-autocomplete/$', ParroquiaAutocomplete.as_view(),
    name='parroquia_autocomplete',
    ),
]

utils/models.py
# -*- encoding: utf-8 -*-
"""!
Modelo que construye los modelos de datos de los usuarios

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
@date 09-06-2017
@version 1.0.0
"""
from django.db import models


class Pais(models.Model):
    """!
    Clase que contiene el modelo de datos de los países

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """
    nombre = models.CharField(max_length=50)

    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Pais'
        verbose_name_plural = 'Paises'

    def __str__(self):
        return self.nombre


class Estado(models.Model):
    """!
    Clase que contiene el modelo de datos de los Estados

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """
    nombre = models.CharField(max_length=50)
    pais = models.ForeignKey(Pais)

    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'


    def __str__(self):
        return self.nombre


class Municipio(models.Model):
    """!
    Clase que contiene el modelo de datos de los Municipios

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """
    estado = models.ForeignKey(Estado)
    nombre = models.CharField(max_length=50)

    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Municipio'
        verbose_name_plural = 'Municipios'

    def __str__(self):
     return self.nombre


class Parroquia(models.Model):
    """!
    Clase que contiene el modelo de datos de  las Parroquias

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """
    municipio = models.ForeignKey(Municipio)
    nombre = models.CharField(max_length=50)
    
    class Meta:
        ordering = ('nombre',)
        verbose_name = 'Parroquia'
        verbose_name_plural = 'Parroquias'

    def __str__(self):
        return self.nombre


class TipoDocumento(models.Model):
    """!
    Clase que contiene el modelo de datos del Tipo de  Documento

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """
    abreviatura = models.CharField(max_length=4, verbose_name='Acrónimo')
    descripcion = models.TextField()

    class Meta:
        ordering = ('abreviatura',)
        verbose_name = 'Tipo Documento'
        verbose_name_plural = 'Tipos Documentos'

    def __str__(self):
        return self.abreviatura

utils/forms.py
# -*- coding: utf-8 -*-
from dal import autocomplete
from django import forms

from .models import (
    Pais, Estado, Municipio, Parroquia
)


class EstadoForm(forms.ModelForm):
    pais = forms.ModelChoiceField(
    queryset=Pais.objects.all(),
    widget=autocomplete.ModelSelect2(url='utils:pais_autocomplete')
    )

    class Meta:
        model = Estado
        fields = ('__all__')


class MunicipioForm(forms.ModelForm):
    estado = forms.ModelChoiceField(
    queryset=Estado.objects.all(),
    widget=autocomplete.ModelSelect2(url='utils:estado_autocomplete')
    )

    class Meta:
        model = Municipio
        fields = ('__all__')


class ParroquiaForm(forms.ModelForm):
    municipio = forms.ModelChoiceField(
    queryset=Municipio.objects.all(),
    widget=autocomplete.ModelSelect2(url='utils:municipio_autocomplete')
    )

    class Meta:
        model = Parroquia
        fields = ('__all__')

utils/views.py
# -*- coding: utf-8 -*-
"""!
Vista que construye los controladores para las utilidades de la plataforma

@author Ing. Leonel P. Hernandez M. (leonelphm at gmail.com)
@copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
@date 09-06-2017
@version 1.0.0
"""
import json
from django.core.serializers.json import DjangoJSONEncoder
from django.http import HttpResponse
from django.shortcuts import render
from dal import autocomplete
from braces.views import GroupRequiredMixin
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.mixins import (
    PermissionRequiredMixin, LoginRequiredMixin
)
from django.shortcuts import (
    redirect
)

from .models import *
from .messages import MENSAJES_LOGIN


class LoginRequeridoPerAuth(LoginRequiredMixin, GroupRequiredMixin):
    """!
    Clase que construye el controlador para el login requerido, se sobreescribe el metodo dispatch

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-06-2017
    @version 1.0.0
    """

    def dispatch(self, request, *args, **kwargs):
        """
        Envia una alerta al usuario que intenta acceder sin permisos para esta clase
        @return: Direcciona al login en caso de no poseer permisos, en caso contrario accede a la clase
        """
        if not request.user.is_authenticated:
            messages.warning(self.request, MENSAJES_LOGIN['LOGIN_REQUERIDO'])
            return self.handle_no_permission()
        valid_group = False
        grupos = request.user.groups.all()
        grupo = []
        if len(grupos) > 1:
            for g in grupos:
                grupo += str(g),
                if (str(g) in self.get_group_required()):
                    valid_group = True
        else:
            try:
                grupo = str(request.user.groups.get())
            except:
                return redirect('users:403error')
            if (grupo in self.get_group_required()):
                valid_group = True
        if not (valid_group):
            return redirect('users:403error')
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class StartView(LoginRequeridoPerAuth, TemplateView):
    """!
    Muestra el inicio de la plataforma

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    @return: El template inicial de la plataforma
    """
    template_name = "utils_start.html"
    group_required = [u"Super Admin", u"Admin", u"Invitado"]


class PaisAutocomplete(autocomplete.Select2QuerySetView):
    """!
    Crea el autocomplete para los Paises

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """
    def get_queryset(self):
        # No se olvide de filtrar los resultados en función del visitante !
        if not self.request.user.is_authenticated():
            return Pais.objects.none()

        qs = Pais.objects.all()
        if self.q:
            qs = qs.filter(nombre__istartswith=self.q)

        return qs


class EstadoAutocomplete(autocomplete.Select2QuerySetView):
    """!
    Crea el autocomplete para los Estados

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """

    def get_queryset(self):
        # No se olvide de filtrar los resultados en función del visitante !
        if not self.request.user.is_authenticated():
            return Estado.objects.none()

        qs = Estado.objects.all()

        if self.q:
            qs = qs.filter(nombre__istartswith=self.q)

        return qs


class MunicipioAutocomplete(autocomplete.Select2QuerySetView):
    """!
    Crea el autocomplete para los Municipios

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """

    def get_queryset(self):
        # No se olvide de filtrar los resultados en función del visitante !
        if not self.request.user.is_authenticated():
            return Municipio.objects.none()

        qs = Municipio.objects.all()

        if self.q:
            qs = qs.filter(nombre__istartswith=self.q)

        return qs


class ParroquiaAutocomplete(autocomplete.Select2QuerySetView):
    """!
    Crea el autocomplete para las Parroquias

    @author Ing. Leonel Paolo Hernandez Macchiarulo  (leonelphm at gmail.com)
    @copyright <a href='http://www.gnu.org/licenses/gpl-2.0.html'>GNU Public License versión 2 (GPLv2)</a>
    @date 09-01-2017
    @version 1.0.0
    """

    def get_queryset(self):
        # No se olvide de filtrar los resultados en función del visitante !
        if not self.request.user.is_authenticated():
            return Parroquia.objects.none()

        qs = Parroquia.objects.all()

        if self.q:
            qs = qs.filter(nombre__istartswith=self.q)

        return qs


def obtenerEstados():
    """
    Función que permite obtener la lista de estados

    El método hace una lista consultando el modelo Estado

    @return: Lista de estados
    """
    try:
        if Estado.DoesNotExist:
            consulta = Estado.objects.all().values('id', 'nombre')
        else:
            consulta = [{'id': '', 'nombre': ''}]
    except:
        consulta = [{'id': '', 'nombre': ''}]

    return consulta

def obtenerMunicipios(request):
    """
    Función que permite obtener la lista de municipios asociados a un estado

    El método hace un llamado al modelo para realizar una consulta

    @param id_estado: Identificador del estado
    @type id_estado: entero

    @return: Lista de municipios asociados al estado
    """
    try:
        if Municipio.DoesNotExist:
            id_estado = request.GET.get('id_estado')
            municipios = Municipio.objects.filter(estado_id=id_estado).values('id', 'nombre')
            data = json.dumps(list(municipios), cls=DjangoJSONEncoder)
            print(data)
        else:
            data = {}
    except:
        data = {}
        pass

    return HttpResponse(data, content_type='application/json')


def obtenerParroquias(request):
    """
    Función que permite obtener la lista de municipios asociados a un estado

    El método hace un llamado al modelo para realizar una consulta

    @param id_estado: Identificador del estado
    @type id_estado: entero

    @return: Lista de municipios asociados al estado
    """
    try:
        if Municipio.DoesNotExist:
            id_municipio = request.GET.get('id_municipio')
            municipios = Parroquia.objects.filter(municipio_id=id_municipio).values('id', 'nombre')
            data = json.dumps(list(municipios), cls=DjangoJSONEncoder)
        else:
            data = {}
    except:
        data = {}
        pass

    return HttpResponse(data, content_type='application/json')


def listMunicipios():
    """
    Función que permite obtener el municipio asociado a una parroquia

    El método hace un llamado a un servicio REST de la aplicación comun

    @param id_parroquia: Identificador de la parroquia
    @type id_parroquia: entero

    @return: El municipio asociado a la parroquia
    """
    try:
        if Municipio.DoesNotExist:
            consulta = Municipio.objects.all().values('id', 'nombre')
        else:
            consulta = [{'id': '', 'nombre': ''}]
    except OperationalError:
        consulta = [{'id': '', 'nombre': ''}]

    return consulta

utils/templates/utils_mensajes.html
<div class="content" id="menu-msn">
        {% block messages %}
            <div class="box-body">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> Error!</h4>
                    No se pudo continuar con la aplicacion debido a los siguientes errores:<br/>
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}<li>{{ field.errors|striptags }}</li>{% endif %}
                        {% endfor %}
                    </ul>
                    </div>
                {% endif %}
                {% for message in messages %}
                    {% if 'success' in message.tags %}
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-check"></i> Exito!</h4>
                            {{ message }}
                         </div>
                    {% elif 'info' in message.tags %}
                        <div class="alert alert-info alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-info"></i> Informacion!</h4>
                            {{ message }}
                      </div>
                    {% elif 'warning' in message.tags %}
                        <div class="alert alert-warning alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-warning"></i> Advertencia!</h4>
                            {{ message }}
                        </div>
                    {% elif 'error' in message.tags %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-ban"></i> Error!</h4>
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endblock messages %}
</div>

utils/templates/utils_start.html
{% extends 'base.html' %}
{% block extras_js %}
{% endblock extras_js %}
{% block contenido %}
 {% block modals %}
              <!-- Modal  -->
              <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title" id="myModalLabel">Actualizar Perfil del Usuario</h4>
                        </div>
                        <div class="modal-body" id="modal-body">
                        </div>
                      </div>
                    </div>
              </div>
            <!-- End Modal -->
        {% endblock modals %}
<div id="wrapper">

        <!-- Sidebar -->
        {% block sidebar %}
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Django Base
                    </a>
                </li>
                {% if 'Super Admin' in request.session.grupos %}
                <li class="submenu">
                    <a href="#" > Gestion de usuarios<span class="caret "></span></a>
                    <ul>
                        <li><a href="{% url 'users:lista_users' %}">Listar Usuarios</a></li>
                        <li><a href="{% url 'users:registrar' %}">Registrar Usuario</a></li>
                  </ul>
                </li>
                {% endif %}
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="{% url 'users:logout' %}">Salir</a>
                </li>
            </ul>
        </div>
        {% endblock sidebar %}
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        {% block content_center %}
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <h1>Simple Sidebar</h1>
                        <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
        {% endblock content_center %}

    </div>
    <!-- /#wrapper -->
{% endblock contenido %}